"""Offline engineering acceptance: untrained CPU RGNN, never scientific claims."""
import json
from pathlib import Path
import urllib.request

import pytest


@pytest.fixture
def synthetic_snapshot(tmp_path, monkeypatch, request):
    import httpx
    import pandas as pd
    import requests
    import torch
    from src.activity import predictor, prediction_service
    from src.agent.planning.task_planner import TaskPlanner
    from tests.family_model_test_support import make_forward_bundle
    from tests.family_real_acceptance_support import read_config, snapshot_family, verify_source

    touched = []

    def forbidden(*args, **kwargs):
        touched.append(True)
        raise AssertionError("offline boundary reached")

    monkeypatch.setenv("MEDCHAT_RUN_FAMILY_REAL_ACCEPTANCE", "0")
    monkeypatch.setattr(torch.cuda, "is_available", lambda: False)
    monkeypatch.setattr(predictor, "get_predictor", forbidden)
    monkeypatch.setattr(predictor.ActivityPredictor, "load", forbidden)
    monkeypatch.setattr(predictor.ActivityPredictor, "_find_checkpoint", forbidden)
    monkeypatch.setattr(TaskPlanner, "plan", forbidden)
    monkeypatch.setattr(httpx.HTTPTransport, "handle_request", forbidden)
    monkeypatch.setattr(httpx.AsyncHTTPTransport, "handle_async_request", forbidden)
    monkeypatch.setattr(requests.Session, "send", forbidden)
    monkeypatch.setattr(urllib.request.OpenerDirector, "open", forbidden)
    family = getattr(request, "param", "PDE")
    threads = torch.get_num_threads()
    prediction_service._family_predictor.cache_clear()
    try:
        torch.set_num_threads(1)
        registry, _ = make_forward_bundle(tmp_path, monkeypatch, family=family,
                                          bundle_id="synthetic-selected")
        config = read_config({"MEDCHAT_RUN_FAMILY_REAL_ACCEPTANCE": "1",
            "MEDCHAT_FAMILY_ACCEPTANCE_MODELS_DIR": str(registry.models_dir),
            "MEDCHAT_FAMILY_ACCEPTANCE_PDE_BUNDLE_ID": "synthetic-selected" if family == "PDE" else "unused-pde",
            "MEDCHAT_FAMILY_ACCEPTANCE_BUCHE_BUNDLE_ID": "synthetic-selected" if family == "BuChE" else "unused-buche"})
        # Source assets above are generated by this test; no original CSV may reopen.
        monkeypatch.setattr(pd, "read_csv", forbidden)
        monkeypatch.setattr("src.activity.family_dataset.load_family_dataset", forbidden)
        original_open = Path.open

        def no_dataset(path, *args, **kwargs):
            if path.suffix.lower() in {".csv", ".tsv"}:
                forbidden()
            return original_open(path, *args, **kwargs)

        monkeypatch.setattr(Path, "open", no_dataset)
        from src.activity.family_contract import resolve_activity_family
        snapshot = snapshot_family(config, resolve_activity_family(family), tmp_path / "snapshot")
        monkeypatch.setenv("ACTIVITY_MODEL_DIR", str(snapshot.models_dir))
        yield snapshot
        assert verify_source(config, snapshot) is True
    finally:
        prediction_service._family_predictor.cache_clear()
        torch.set_num_threads(threads)
        assert not touched, "Offline guard reached, including swallowed exceptions"


@pytest.mark.parametrize("synthetic_snapshot", ["PDE", "BuChE"], indirect=True)
def test_same_snapshot_reaches_all_real_entrypoints(synthetic_snapshot, tmp_path):
    from tests.family_acceptance_chain_support import run_family_chain
    report = run_family_chain(synthetic_snapshot, work_dir=tmp_path / "chain", mode="synthetic_fixture")
    assert report["status"] == "passed", report
    assert report["mode"] == "synthetic_fixture"
    assert report["decision_model"] == "scripted"
    assert report["expected_identity"] == report["actual_identity"]
    assert set(report["stages"]) == {"predictor", "api_single", "api_batch", "tool", "decision", "websocket", "dom"}
    assert all(stage["status"] == "passed" for stage in report["stages"].values())
    assert [row["smiles"] for row in report["stages"]["api_batch"]["rows"]] == ["CCO", "CCN", "CCO"]
    assert report["stages"]["dom"]["rows"] == 3
    assert report["stages"]["tool"]["observation_status"] == "succeeded"
    assert report["stages"]["tool"]["checks"]["formatted_numbers"] is True
    for name in ("decision", "websocket"):
        stage = report["stages"][name]
        assert stage["agent_status"] == "completed"
        assert stage["model_calls"] == 2
        assert stage["tool_trace"][0]["input_digest"]
        assert stage["checks"]["observed_evidence"] is True
        assert stage["checks"]["input_digest"] is True
    assert report["stages"]["websocket"]["checks"]["terminal"] is True
    decision = report["stages"]["decision"]
    websocket = report["stages"]["websocket"]
    assert decision["trace_id"] != websocket["trace_id"]
    assert decision["tool_trace"][0]["evidence_id"] != websocket["tool_trace"][0]["evidence_id"]
    encoded = json.dumps(report, allow_nan=False)
    assert len(encoded.encode()) < 1024 * 1024
    assert str(tmp_path) not in encoded
    assert "model_config" not in encoded and "weights_file" not in encoded
    from src.activity import prediction_service
    assert prediction_service._family_predictor.cache_info().currsize == 0


@pytest.mark.parametrize("synthetic_snapshot", ["PDE", "BuChE"], indirect=True)
@pytest.mark.parametrize("bad_input", ["smiles", "target"])
def test_invalid_inputs_are_not_model_unavailability(synthetic_snapshot, tmp_path, monkeypatch, bad_input):
    from fastapi import FastAPI
    from fastapi.testclient import TestClient
    from src.activity import prediction_service
    from src.agent.tools.activity_predictor_tool import ActivityPredictorTool
    from src.web.routes.api_routes import setup_api_routes
    from tests.family_acceptance_chain_support import ALIASES, decision_session, invoke_decision, websocket_decision
    target = "AChE" if bad_input == "target" else ALIASES[synthetic_snapshot.family_id][1]
    smiles = "CC(C)((" if bad_input == "smiles" else "CCO"
    app = FastAPI()
    setup_api_routes(app)
    with TestClient(app) as client:
        responses = [client.post("/api/activity/predict", data={"smiles": smiles, "target": target}),
                     client.post("/api/activity/batch_predict", data={"target": target},
                                 files={"file": ("invalid.smi", smiles.encode(), "text/plain")})]
    for response in responses:
        assert response.status_code == 200
        body = response.json()
        assert body["status"] == "failed" and not body["success"]
        row = body["results"][0]
        assert row["predicted_pIC50"] is row["activity_probability"] is None
        assert row["errors"].get("input") and "bundle" not in row["errors"]

    def no_service(*args, **kwargs):
        pytest.fail("Invalid parsing must not call the scientific service")

    monkeypatch.setattr(prediction_service, "predict_activity", no_service)
    tool = ActivityPredictorTool().execute({"smiles": smiles, "target": target})
    assert tool.status.value == "invalid_input"
    assert tool.error.code.value == "invalid_input" and tool.data is None
    for transport in (False, True):
        with decision_session(tmp_path, target=target, query=f"SMILES: {smiles}") as session:
            if transport:
                result, frames = websocket_decision(session)
                assert len([f for f in frames if f["type"] == "complete"]) == 1
                assert len([f for f in frames if f["type"] == "agent_result"]) == 1
                assert frames[-1]["type"] == "complete"
                assert frames[-1]["trace_id"] == session.context.trace_id
                assert not any(f["type"] == "molecular_generation" for f in frames)
            else:
                result = invoke_decision(session)
            assert not result.success and result.to_legacy_dict()["status"] in {"failed", "rejected"}
            assert '"predicted_pIC50":' not in result.final_answer
            for output in session.outputs:
                assert output.error.code.value == "invalid_input"
                assert output.data is None


@pytest.mark.parametrize("damage", ["missing_weights", "bad_card", "bad_hash", "missing_stage"])
def test_damaged_copy_fails_without_fallback_and_keeps_stage_errors(synthetic_snapshot, tmp_path, damage):
    from src.activity.model_registry import REGISTRY_STATE_FILE
    from tests.family_acceptance_chain_support import run_family_chain
    snapshot = synthetic_snapshot
    model = snapshot.expected_models["regression"]
    if damage == "missing_weights":
        (snapshot.models_dir / model["weights_file"]).unlink()
    elif damage == "bad_card":
        (snapshot.models_dir / model["model_card_file"]).write_text("{}", encoding="utf-8")
    elif damage == "bad_hash":
        with (snapshot.models_dir / model["weights_file"]).open("ab") as handle:
            handle.write(b"synthetic-corruption")
    else:
        path = snapshot.models_dir / REGISTRY_STATE_FILE
        state = json.loads(path.read_bytes())
        del state["family_bundles"][snapshot.bundle_id]["models"]["regression"]
        path.write_text(json.dumps(state), encoding="utf-8")
    report = run_family_chain(snapshot, work_dir=tmp_path / "chain", mode="synthetic_fixture")
    assert report["status"] == "failed"
    stage = report["stages"]["predictor"]
    assert stage["status"] == "failed"
    if damage == "missing_stage":
        # Registry rejects the incomplete mapping before a predictor can emit rows.
        assert report["reason"] == stage["error"] == "invalid_registry"
        assert stage["rows"] == []
        return
    assert report["reason"] == "chain_mismatch"
    assert report["actual_identity"]["family_id"] == synthetic_snapshot.family_id
    assert report["actual_identity"]["bundle_id"] is None
    for row in stage["rows"]:
        assert row["status"] == "failed"
        assert row["errors"] == {"bundle": "family_model_bundle_unavailable_or_invalid"}
        assert row["predicted_pIC50"] is row["activity_probability"] is None


@pytest.mark.parametrize("damage", ["family", "smiles", "empty", "demo", "fallback", "wrong_hash",
                                     "bool_pic50", "numeric_drift", "threshold", "warnings", "errors", "class"])
def test_service_corruption_cannot_count_as_forward_success(synthetic_snapshot, tmp_path, monkeypatch, damage):
    from src.activity import prediction_service
    from tests.family_acceptance_chain_support import run_family_chain
    original = prediction_service.predict_activity

    def corrupted(*args, **kwargs):
        summary = original(*args, **kwargs)
        row = summary["results"][0]
        if damage == "family":
            row["family_id"] = "buche-family"
        elif damage == "smiles":
            row["smiles"] = "CCC"
        elif damage == "empty":
            summary["results"] = []
        elif damage in {"bool_pic50", "numeric_drift", "threshold", "warnings", "errors", "class"}:
            row.update({"bool_pic50": {"predicted_pIC50": True},
                        "numeric_drift": {"predicted_pIC50": row["predicted_pIC50"] + .01},
                        "threshold": {"label_threshold": 6.0},
                        "warnings": {"warnings": ["injected-warning"]},
                        "errors": {"errors": {"regression": "injected-error"}},
                        "class": {"activity_class": "unsupported"}}[damage])
        else:
            model = row["provenance"]["models"]["regression"]
            model.update({"demo": {"demo_mode": True}, "fallback": {"fallback_used": True},
                          "wrong_hash": {"weights_sha256": "0" * 64}}[damage])
        return summary

    monkeypatch.setattr(prediction_service, "predict_activity", corrupted)
    report = run_family_chain(synthetic_snapshot, work_dir=tmp_path / "chain", mode="synthetic_fixture")
    assert report["status"] == "failed" and report["reason"] == "chain_mismatch"
    assert report["stages"]["predictor"]["status"] == "passed"
    assert report["stages"]["api_single"]["status"] == "failed"
    assert "decision" not in report["stages"]


def test_partial_forward_keeps_classification_and_both_pins(synthetic_snapshot, tmp_path, monkeypatch):
    from src.activity.family_predictor import _PinnedPredictor
    from tests.family_acceptance_chain_support import run_family_chain
    original = _PinnedPredictor.predict

    def fail_regression(self, smiles):
        if self._metadata["task_type"] == "regression":
            return [{"smiles": smi, "success": False} for smi in smiles]
        return original(self, smiles)

    monkeypatch.setattr(_PinnedPredictor, "predict", fail_regression)
    report = run_family_chain(synthetic_snapshot, work_dir=tmp_path / "chain", mode="synthetic_fixture")
    assert report["status"] == "failed"
    for row in report["stages"]["predictor"]["rows"]:
        assert row["status"] == "partial" and row["predicted_pIC50"] is None
        assert 0 <= row["activity_probability"] <= 1
        assert row["errors"] == {"regression": "regression_failed_or_invalid_output"}
        assert set(row["models"]) == {"classification", "regression"}


@pytest.mark.parametrize("synthetic_snapshot", ["PDE", "BuChE"], indirect=True)
def test_clarification_uses_current_molecule_not_previous_evidence(synthetic_snapshot, tmp_path):
    from src.agent.contracts.decision import ClarifyDecision
    from src.activity.prediction_service import predict_activity
    from tests.family_acceptance_chain_support import (
        ALIASES, activity_decision, decision_session, finish_observed, invoke_decision, check_rows,
    )
    target = ALIASES[synthetic_snapshot.family_id][1]
    clarify = ClarifyDecision(version="1", action="clarify", question="Provide corrected input", missing_fields=["smiles"])
    with decision_session(tmp_path, target=target, query="SMILES: CCO",
                          decisions=[activity_decision(), clarify, activity_decision(), finish_observed]) as session:
        waiting = invoke_decision(session)
        assert waiting.metadata["waiting_for_input"]
        old_id = waiting.tool_results[0].quality["evidence_id"]
        result = invoke_decision(session, continuation_id=waiting.metadata["continuation_id"], clarified_query="SMILES: CCN")
        assert result.success, result.metadata
        assert session.inputs == [{"query": "SMILES: CCO", "target": target}, {"query": "SMILES: CCN", "target": target}]
        answer = json.loads(result.final_answer.removeprefix("```json\n").removesuffix("\n```"))
        assert answer["evidence_id"] != old_id
        assert old_id not in result.final_answer
        check_rows(answer["data"], predict_activity(["CCN"], target=target)["results"], synthetic_snapshot, target=target)


def test_clarification_cannot_silently_change_target(synthetic_snapshot, tmp_path):
    from src.agent.contracts.decision import ClarifyDecision
    from tests.family_acceptance_chain_support import activity_decision, decision_session, invoke_decision
    clarify = ClarifyDecision(version="1", action="clarify", question="Provide input", missing_fields=["smiles"])
    with decision_session(tmp_path, target="PDE5A", query="SMILES: CCO",
                          decisions=[activity_decision(), clarify, activity_decision()]) as session:
        waiting = invoke_decision(session)
        result = invoke_decision(session, continuation_id=waiting.metadata["continuation_id"],
                                 clarified_query="靶点：BuChE；SMILES: CCN")
        assert not result.success
        assert len(session.inputs) == 1
        assert result.metadata["stop_reason"] == "activity_target_conflict_or_unknown"
        assert '"predicted_pIC50":' not in result.final_answer


def test_unauthorized_activity_decision_never_executes(synthetic_snapshot, tmp_path):
    from tests.family_acceptance_chain_support import decision_session, invoke_decision
    with decision_session(tmp_path, target="PDE5A", query="SMILES: CCO") as session:
        result = invoke_decision(session, allowed_tools=set())
        assert not result.success
        assert result.metadata["stop_reason"] == "tool_not_authorized"
        assert session.inputs == session.outputs == []


def test_node_receives_actual_summary_and_bounded_remaining_time(synthetic_snapshot, tmp_path, monkeypatch):
    from types import SimpleNamespace
    from tests import family_acceptance_chain_support as chain
    from tests.family_acceptance_process_support import ChildResult
    calls = []
    now = [0.0]
    original_check = chain.check_decision

    def clock_after_websocket(*args, **kwargs):
        checked = original_check(*args, **kwargs)
        if args[-1] is not None:
            now[0] = 105.0
        return checked

    monkeypatch.setattr(chain, "time", SimpleNamespace(monotonic=lambda: now[0]))
    monkeypatch.setattr(chain, "check_decision", clock_after_websocket)

    def inspect_child(argv, *, env, cwd, timeout):
        calls.append(argv)
        assert Path(argv[0]).is_absolute() and Path(argv[0]).name.lower() in {"node", "node.exe"}
        assert argv[-2] == "--input"
        summary = json.loads(Path(argv[-1]).read_bytes())
        assert [row["smiles"] for row in summary["results"]] == chain.SMILES
        assert summary["status"] == "passed"
        assert "ACTIVITY_MODEL_DIR" not in env
        assert timeout == 15.0  # min(30, remaining family budget), not a fresh 30s.
        return ChildResult("failed", "child_timeout", None, None, True, True)

    monkeypatch.setattr(chain, "run_owned_child", inspect_child)
    report = chain.run_family_chain(synthetic_snapshot, work_dir=tmp_path / "chain", mode="synthetic_fixture")
    assert calls
    assert report["status"] == "failed" and report["reason"] == "child_timeout"
    assert report["stages"]["websocket"]["status"] == "passed"
    assert report["stages"]["dom"]["status"] == "failed"


def test_rejected_finish_preserves_actual_tool_and_agent_failure(synthetic_snapshot, tmp_path, monkeypatch):
    from src.agent.contracts.decision import FinishDecision
    from tests import family_acceptance_chain_support as chain

    def stale_evidence(messages):
        return FinishDecision(version="1", action="finish", response_kind="scientific",
                              text="Not evidence", evidence_ids=["old-unrelated-evidence"])

    monkeypatch.setattr(chain, "finish_observed", stale_evidence)
    report = chain.run_family_chain(synthetic_snapshot, work_dir=tmp_path / "chain", mode="synthetic_fixture")
    assert report["status"] == "failed" and report["reason"] == "chain_mismatch"
    stage = report["stages"]["decision"]
    assert stage["status"] == "failed"
    # A successful tool followed by a rejected finish is an Agent partial,
    # while the acceptance verdict must still be failed.
    assert stage["agent_status"] == "partial"
    assert stage["stop_reason"] == "evidence_not_usable_in_this_trace"
    assert stage["tool_trace"][0]["input_digest"]
    assert stage["rows"][0]["status"] == "passed"
    assert stage["rows"][0]["models"]["regression"]["weights_sha256"] == synthetic_snapshot.expected_models["regression"]["weights_sha256"]


def test_websocket_lost_scientific_evidence_cannot_pass(synthetic_snapshot, tmp_path, monkeypatch):
    from tests import family_acceptance_chain_support as chain
    original = chain.websocket_decision

    def truncated(session):
        result, frames = original(session)
        public = next(frame for frame in frames if frame["type"] == "agent_result")
        public["tool_result_sequence"][0]["data"][0]["predicted_pIC50"] = None
        public["display_redacted_or_truncated"] = True
        return result, frames

    monkeypatch.setattr(chain, "websocket_decision", truncated)
    report = chain.run_family_chain(synthetic_snapshot, work_dir=tmp_path / "chain", mode="synthetic_fixture")
    assert report["status"] == "failed"
    assert report["stages"]["decision"]["status"] == "passed"
    assert report["stages"]["websocket"]["status"] == "failed"
    assert report["stages"]["websocket"]["agent_status"] == "completed"


def test_bounded_report_cannot_pass_when_evidence_is_oversized(synthetic_snapshot, tmp_path, monkeypatch):
    from tests import family_acceptance_chain_support as chain
    original = chain.decision_record

    def oversized(*args, **kwargs):
        record = original(*args, **kwargs)
        record["tool_trace"][0]["warnings"] = ["x" * 513]
        return record

    monkeypatch.setattr(chain, "decision_record", oversized)
    report = chain.run_family_chain(synthetic_snapshot, work_dir=tmp_path / "chain", mode="synthetic_fixture")
    assert report["status"] == "failed" and report["reason"] == "invalid_report"
    assert "x" * 513 not in json.dumps(report)


def test_settings_and_caches_restore_even_when_node_is_missing(synthetic_snapshot, tmp_path, monkeypatch):
    import os
    import torch
    from src.activity import prediction_service
    from tests import family_acceptance_chain_support as chain
    original_dir = os.environ["ACTIVITY_MODEL_DIR"]
    original_cuda = torch.cuda.is_available
    threads = torch.get_num_threads()
    monkeypatch.setattr(chain.shutil, "which", lambda _: None)
    report = chain.run_family_chain(synthetic_snapshot, work_dir=tmp_path / "chain", mode="synthetic_fixture")
    assert report["status"] == "failed" and report["reason"] == "dependency_unavailable"
    assert os.environ["ACTIVITY_MODEL_DIR"] == original_dir
    assert torch.cuda.is_available is original_cuda and torch.get_num_threads() == threads
    assert prediction_service._family_predictor.cache_info().currsize == 0
