from enum import Enum


class TaskErrorCode(str, Enum):
    TASK_INPUT_INVALID = "TASK_INPUT_INVALID"
    TASK_INPUT_HASH_MISMATCH = "TASK_INPUT_HASH_MISMATCH"
    TASK_BACKEND_UNAVAILABLE = "TASK_BACKEND_UNAVAILABLE"
    TEMPORAL_START_FAILED = "TEMPORAL_START_FAILED"
    TEMPORAL_WORKER_UNAVAILABLE = "TEMPORAL_WORKER_UNAVAILABLE"
    TASK_HEARTBEAT_TIMEOUT = "TASK_HEARTBEAT_TIMEOUT"
    TASK_CANCEL_TIMEOUT = "TASK_CANCEL_TIMEOUT"
    DOCKING_ENVIRONMENT_UNAVAILABLE = "DOCKING_ENVIRONMENT_UNAVAILABLE"
    DOCKING_PROCESS_FAILED = "DOCKING_PROCESS_FAILED"
    DOCKING_PROCESS_OWNERSHIP_UNCERTAIN = "DOCKING_PROCESS_OWNERSHIP_UNCERTAIN"
    DOCKING_ARTIFACT_INVALID = "DOCKING_ARTIFACT_INVALID"
    SCIENTIFIC_VALIDATION_FAILED = "SCIENTIFIC_VALIDATION_FAILED"
    TASK_PROJECTION_FAILED = "TASK_PROJECTION_FAILED"
