"""C0a pure proposals: no admission, transport, consent or execution proof.

Fixtures are literal contract examples, not generated by a production validator.
Only boundary-order tests observe model_validate, delegating to the real method.
"""
import importlib
import json
import traceback

import pytest
from pydantic import ValidationError

from src.agent.contracts.decision import DecisionProtocolError


MINIMAL = (
    '{"proposal":{"version":"1","kind":"docking_request",'
    '"unresolved":true,"source_spans":[],"fields":{}}}'
)
KINDS = (
    "not_c", "docking_request", "docking_refinement",
    "docking_observation", "mixed", "uncertain",
)
PROPOSAL_FIELDS = {"version", "kind", "unresolved", "source_spans", "fields"}
INPUT_FIELDS = {
    "receptor_ref", "ligand_ref", "center", "size", "exhaustiveness", "num_modes"
}
ERROR = "invalid_docking_preparation"


def contract():
    # An absent feature is an explicit test failure, never a collection skip.
    # Missing transitive dependencies must retain their own failure identity.
    name = "src.agent.contracts.docking_preparation"
    try:
        return importlib.import_module(name)
    except ModuleNotFoundError as exc:
        if exc.name != name:
            raise
        pytest.fail("C0a docking preparation contract is absent", pytrace=False)


def proposal():
    return json.loads(MINIMAL)["proposal"]


def supplied_proposal():
    # Synthetic descriptors only. No source existence/ownership is asserted.
    return {
        "version": "1", "kind": "docking_request", "unresolved": False,
        "source_spans": [
            {"source_id": "query", "start": 0, "end": 1, "role": "request"},
            {"source_id": "attachment-1", "start": 0, "end": 1, "role": "field"},
            {"source_id": "attachment-2", "start": 0, "end": 1, "role": "field"},
            {"source_id": "refinement", "start": 0, "end": 3, "role": "field"},
        ],
        "fields": {
            "receptor_ref": {"value": "attachment-1", "span_indices": [1]},
            "ligand_ref": {"value": "attachment-2", "span_indices": [2]},
            "center": {"value": [-2, 0.0, 3.5], "span_indices": [3]},
            "size": {"value": [1, 20.5, 100], "span_indices": [3]},
            "exhaustiveness": {"value": 1, "span_indices": [3]},
            "num_modes": {"value": 50, "span_indices": [3]},
        },
    }


def wire(data):
    return json.dumps({"proposal": data}, ensure_ascii=False, separators=(",", ":"))


def reject_raw(api, raw):
    with pytest.raises(DecisionProtocolError) as caught:
        api.parse_docking_preparation_json(raw)
    error = caught.value
    assert error.code == ERROR
    assert error.args == (ERROR,)
    assert error.schema_issues == []
    assert error.__cause__ is None
    rendered = "".join(traceback.format_exception(type(error), error, error.__traceback__))
    public = str(error) + repr(error) + repr(vars(error)) + rendered
    assert "private-value-marker" not in public


def reject_proposal(api, data):
    reject_raw(api, wire(data))
    with pytest.raises(ValidationError):
        api.DockingPreparationProposal(**data)
    with pytest.raises(ValidationError):
        api.DockingPreparationEnvelope(proposal=data)


def observe_validation(api, monkeypatch):
    """Keep real validation; positive control proves the observation is live."""
    visited = []
    original = api.DockingPreparationEnvelope.model_validate

    def observe(cls, value, *args, **kwargs):
        visited.append(True)
        return original(value, *args, **kwargs)

    monkeypatch.setattr(api.DockingPreparationEnvelope, "model_validate", classmethod(observe))
    assert api.parse_docking_preparation_json(MINIMAL).kind == "docking_request"
    assert visited == [True]
    visited.clear()
    return visited


def test_minimal_proposal_is_not_execution_authority():
    api = contract()
    value = api.parse_docking_preparation_json(MINIMAL)
    assert isinstance(value, api.DockingPreparationProposal)
    assert set(value.model_dump()) == PROPOSAL_FIELDS
    assert value.model_dump(exclude_unset=True) == proposal()
    assert value.fields.model_dump(exclude_unset=True) == {}
    assert not any(hasattr(value, name) for name in (
        "execute", "approve", "approval_nonce", "owner", "task_id", "authorized"
    ))


@pytest.mark.parametrize("kind", KINDS)
@pytest.mark.parametrize("unresolved", [False, True])
def test_kinds_and_native_boolean_contract(kind, unresolved):
    api = contract()
    data = proposal()
    data.update(kind=kind, unresolved=unresolved)
    if kind in {"mixed", "uncertain"} and unresolved is False:
        reject_proposal(api, data)
        return
    parsed = api.parse_docking_preparation_json(wire(data))
    assert parsed.model_dump(exclude_unset=True) == data
    assert type(parsed.unresolved) is bool
    assert api.DockingPreparationProposal(**data) == parsed
    assert api.DockingPreparationEnvelope(proposal=data).proposal == parsed
    # Refinement/history/source authority remains a later server-entry check.


@pytest.mark.parametrize("kind", ["docking_request", "docking_refinement"])
def test_full_literal_inputs_preserved_without_inferred_defaults(kind):
    api = contract()
    data = supplied_proposal()
    data["kind"] = kind
    assert api.parse_docking_preparation_json(wire(data)).model_dump(exclude_unset=True) == data
    assert api.DockingPreparationEnvelope(proposal=data).model_dump(exclude_unset=True) == {
        "proposal": data
    }


@pytest.mark.parametrize("name", sorted(INPUT_FIELDS))
def test_each_input_is_independently_optional_but_never_explicit_null(name):
    api = contract()
    data = supplied_proposal()
    data["fields"] = {name: data["fields"][name]}
    assert api.parse_docking_preparation_json(wire(data)).fields.model_dump(exclude_unset=True) == data["fields"]
    data["fields"][name] = None
    reject_proposal(api, data)


@pytest.mark.parametrize("kind", ["not_c", "mixed", "uncertain", "docking_observation"])
def test_non_preparation_kinds_cannot_carry_input_fields(kind):
    api = contract()
    data = supplied_proposal()
    data.update(kind=kind, unresolved=True)
    reject_proposal(api, data)


@pytest.mark.parametrize("name", sorted(PROPOSAL_FIELDS))
def test_all_five_proposal_fields_required(name):
    api = contract()
    data = proposal()
    del data[name]
    reject_proposal(api, data)


@pytest.mark.parametrize("data", [{}, {"proposal": None}, {"proposal": []}, {"proposal": False}])
def test_direct_envelope_requires_one_proposal_object(data):
    api = contract()
    reject_raw(api, json.dumps(data))
    with pytest.raises(ValidationError):
        api.DockingPreparationEnvelope(**data)


@pytest.mark.parametrize("location", ["envelope", "proposal", "fields", "span", "input"])
@pytest.mark.parametrize("name", ["private-value-marker", "owner", "approval_nonce", "task_id", "execute"])
def test_closed_objects_reject_extra_keys_at_every_layer(location, name):
    api = contract()
    data = {"proposal": supplied_proposal()}
    targets = {
        "envelope": data, "proposal": data["proposal"],
        "fields": data["proposal"]["fields"],
        "span": data["proposal"]["source_spans"][0],
        "input": data["proposal"]["fields"]["center"],
    }
    targets[location][name] = "private-value-marker"
    reject_raw(api, json.dumps(data))
    with pytest.raises(ValidationError):
        api.DockingPreparationEnvelope(**data)


@pytest.mark.parametrize("field,value", [
    ("version", 1), ("version", True), ("version", 1.0), ("version", "2"),
    ("version", None), ("version", " 1"), ("version", []),
    ("kind", 1), ("kind", None), ("kind", "tool"), ("kind", "Docking_request"),
    ("kind", "docking_request "), ("kind", {}), ("kind", []),
    ("unresolved", 0), ("unresolved", 1), ("unresolved", 0.0),
    ("unresolved", "true"), ("unresolved", "false"), ("unresolved", None),
    ("unresolved", []), ("unresolved", {}),
    ("source_spans", None), ("source_spans", {}), ("source_spans", "query"),
    ("fields", None), ("fields", []), ("fields", False),
])
def test_top_level_strict_types(field, value):
    api = contract()
    data = proposal()
    data[field] = value
    reject_proposal(api, data)


@pytest.mark.parametrize("role", ["request", "field", "extra_obligation"])
@pytest.mark.parametrize("source_id", ["query", "refinement", "attachment-1", "a" * 128])
def test_span_roles_and_source_id_boundaries(role, source_id):
    api = contract()
    data = proposal()
    # Indices are code points, not bytes/UTF-16. The DTO has no source text and
    # must not pretend to check existence, ownership or text upper bounds.
    data["source_spans"] = [{"source_id": source_id, "start": 1, "end": 2, "role": role}]
    assert api.parse_docking_preparation_json(wire(data)).model_dump(exclude_unset=True) == data


@pytest.mark.parametrize("field", ["source_id", "start", "end", "role"])
def test_span_fields_are_required(field):
    api = contract()
    data = supplied_proposal()
    del data["source_spans"][0][field]
    reject_proposal(api, data)


@pytest.mark.parametrize("value", [None, [], False, 1, "query"])
def test_span_items_must_be_objects(value):
    api = contract()
    data = proposal()
    data["source_spans"] = [value]
    reject_proposal(api, data)


@pytest.mark.parametrize("field,value", [
    ("source_id", ""), ("source_id", "a" * 129), ("source_id", 1),
    ("source_id", None), ("source_id", "/tmp/receptor.pdb"),
    ("source_id", "D:\\private\\receptor.pdb"), ("source_id", "https://example.invalid/a"),
    ("start", -1), ("start", True), ("start", 0.0), ("start", "0"),
    ("start", None), ("start", 1), ("start", 2),
    ("end", 0), ("end", -1), ("end", False), ("end", 1.0),
    ("end", "1"), ("end", None),
    ("role", "execute"), ("role", "FIELD"), ("role", None), ("role", 1),
])
def test_invalid_span_types_ranges_and_non_opaque_sources(field, value):
    api = contract()
    data = supplied_proposal()
    data["source_spans"][0][field] = value
    reject_proposal(api, data)


@pytest.mark.parametrize("count", [0, 16, 17])
def test_source_span_count_limit(count):
    api = contract()
    data = proposal()
    data["source_spans"] = [
        {"source_id": "query", "start": i, "end": i + 1, "role": "field"}
        for i in range(count)
    ]
    if count == 17:
        reject_proposal(api, data)
    else:
        assert api.parse_docking_preparation_json(wire(data)).model_dump(exclude_unset=True) == data


@pytest.mark.parametrize("field", ["value", "span_indices"])
@pytest.mark.parametrize("name", sorted(INPUT_FIELDS))
def test_input_records_require_both_members(name, field):
    api = contract()
    data = supplied_proposal()
    del data["fields"][name][field]
    reject_proposal(api, data)


@pytest.mark.parametrize("name", sorted(INPUT_FIELDS))
@pytest.mark.parametrize("value", [[], False, 1, "private-value-marker"])
def test_input_records_are_objects_not_bare_values(name, value):
    api = contract()
    data = supplied_proposal()
    data["fields"][name] = value
    reject_proposal(api, data)


def test_input_cannot_reference_an_absent_span():
    api = contract()
    data = supplied_proposal()
    data["source_spans"] = []
    reject_proposal(api, data)


@pytest.mark.parametrize("indices", [[], [0, 0], [-1], [4], [True], [0.0], ["0"], [None],
                                     [0, 1, 2, 3, 0], None, {}, "0"])
def test_span_indices_are_distinct_bounded_native_integers(indices):
    api = contract()
    data = supplied_proposal()
    data["fields"]["center"]["span_indices"] = indices
    reject_proposal(api, data)


@pytest.mark.parametrize("indices", [[0], [3], [0, 1, 2, 3]])
def test_one_through_four_valid_span_indices(indices):
    api = contract()
    data = supplied_proposal()
    data["fields"]["center"]["span_indices"] = indices
    assert api.parse_docking_preparation_json(wire(data)).model_dump(exclude_unset=True) == data


@pytest.mark.parametrize("name,value", [
    ("center", []), ("center", [1, 2]), ("center", [1, 2, 3, 4]),
    ("center", [True, 2, 3]), ("center", ["1", 2, 3]), ("center", [None, 2, 3]),
    ("center", [float("nan"), 2, 3]), ("center", [float("inf"), 2, 3]),
    ("center", [float("-inf"), 2, 3]), ("center", None), ("center", {}),
    ("size", [0, 20, 20]), ("size", [-1, 20, 20]), ("size", [100.01, 20, 20]),
    ("size", [True, 20, 20]), ("size", ["20", 20, 20]), ("size", [1, 2]),
    ("size", [1, 2, 3, 4]), ("size", [float("nan"), 20, 20]),
    ("size", [float("inf"), 20, 20]), ("size", None),
    ("exhaustiveness", 0), ("exhaustiveness", 65), ("exhaustiveness", True),
    ("exhaustiveness", 1.0), ("exhaustiveness", "1"), ("exhaustiveness", None),
    ("num_modes", 0), ("num_modes", 51), ("num_modes", True),
    ("num_modes", 1.0), ("num_modes", "1"), ("num_modes", None),
    ("receptor_ref", ""), ("receptor_ref", "a" * 129), ("receptor_ref", 1),
    ("receptor_ref", None), ("receptor_ref", "/tmp/receptor.pdb"),
    ("ligand_ref", ""), ("ligand_ref", "a" * 129), ("ligand_ref", False),
    ("ligand_ref", None), ("ligand_ref", "https://example.invalid/ligand.sdf"),
])
def test_field_specific_values_reject_coercion_and_out_of_bounds(name, value):
    api = contract()
    data = supplied_proposal()
    data["fields"][name]["value"] = value
    reject_proposal(api, data)


@pytest.mark.parametrize("name,value", [
    ("center", [-1e100, 0, 1e100]), ("size", [0.01, 1, 100]),
    ("exhaustiveness", 64), ("num_modes", 1),
    ("receptor_ref", "a" * 128), ("ligand_ref", "b" * 128),
])
def test_valid_value_boundaries_do_not_invent_server_authority(name, value):
    api = contract()
    data = supplied_proposal()
    data["fields"][name]["value"] = value
    assert api.parse_docking_preparation_json(wire(data)).model_dump(exclude_unset=True) == data


class CustomString(str):
    pass


class CustomInt(int):
    pass


class CustomFloat(float):
    pass


class CustomList(list):
    pass


class CustomDict(dict):
    pass


@pytest.mark.parametrize("path,value", [
    (("version",), b"1"), (("version",), CustomString("1")),
    (("kind",), CustomString("docking_request")),
    (("unresolved",), CustomInt(1)), (("source_spans",), ()),
    (("source_spans",), CustomList()), (("fields",), CustomDict()),
    (("source_spans", 0), CustomDict(source_id="query", start=0, end=1, role="request")),
    (("source_spans", 0, "start"), CustomInt(0)),
    (("source_spans", 0, "source_id"), b"query"),
    (("fields", "center", "value"), (1, 2, 3)),
    (("fields", "center", "value"), [CustomFloat(1), 2, 3]),
    (("fields", "center", "span_indices"), (0,)),
    (("fields", "center", "span_indices"), [CustomInt(0)]),
    (("fields", "receptor_ref", "value"), b"attachment-1"),
])
def test_direct_dtos_reject_non_native_types_without_json_normalizing_them(path, value):
    api = contract()
    data = supplied_proposal()
    target = data
    for key in path[:-1]:
        target = target[key]
    target[path[-1]] = value
    with pytest.raises(ValidationError):
        api.DockingPreparationProposal(**data)
    with pytest.raises(ValidationError):
        api.DockingPreparationEnvelope(proposal=data)


@pytest.mark.parametrize("raw", [None, False, 0, {}, [], b"{}", CustomString(MINIMAL), ""])
def test_parser_requires_native_nonempty_string(raw):
    reject_raw(contract(), raw)


@pytest.mark.parametrize("raw", [
    " ", "{", "{'proposal': {}}", '{"proposal":{},}',
    "```json\n" + MINIMAL + "\n```", "prefix " + MINIMAL,
    MINIMAL + " suffix", MINIMAL + MINIMAL, "//comment\n" + MINIMAL,
    "\ufeff" + MINIMAL, "null", "true", "1", '"private-value-marker"', "[]",
    "{}", '{"proposal":null}', '{"proposal":[]}', '{"proposal":false}',
    '{"proposal":"private-value-marker"}',
])
def test_whole_json_envelope_only_no_repair_or_extraction(raw):
    reject_raw(contract(), raw)


@pytest.mark.parametrize("old,new", [
    ('"proposal":', '"proposal":{},"proposal":'),
    ('"version":"1"', '"version":"1","version":"1"'),
    ('"kind":', '"\\u006bind":"not_c","kind":'),
    ('"fields":{', '"fields":{"center":{},'),
    ('"source_id":"query"', '"source_id":"query","source_id":"query"'),
    ('"span_indices":[3]', '"span_indices":[3],"span_indices":[3]'),
    ('"value":1', '"value":1,"value":1'),
])
def test_duplicate_keys_reject_before_schema_even_if_values_match(old, new, monkeypatch):
    api = contract()
    raw = wire(supplied_proposal())
    assert old in raw
    raw = raw.replace(old, new, 1)
    visited = observe_validation(api, monkeypatch)
    reject_raw(api, raw)
    assert visited == []


@pytest.mark.parametrize("number", ["NaN", "Infinity", "-Infinity", "1e999", "-1e999"])
def test_nonfinite_json_rejects_before_model_validation(number, monkeypatch):
    api = contract()
    raw = wire(supplied_proposal())
    assert '"value":1,' in raw
    raw = raw.replace('"value":1,', '"value":' + number + ',', 1)
    visited = observe_validation(api, monkeypatch)
    reject_raw(api, raw)
    assert visited == []


@pytest.mark.parametrize("raw", ["\ud800", '{"proposal":"\\ud800"}', '{"\\udfff":{}}'])
def test_surrogates_reject_before_model_validation(raw, monkeypatch):
    api = contract()
    visited = observe_validation(api, monkeypatch)
    reject_raw(api, raw)
    assert visited == []


@pytest.mark.parametrize("size", [8191, 8192, 8193])
def test_exact_byte_boundary_includes_whitespace(size, monkeypatch):
    api = contract()
    raw = "\r\n\t " + MINIMAL
    raw += " " * (size - len(raw.encode("utf-8")))
    assert len(raw.encode("utf-8")) == size
    visited = observe_validation(api, monkeypatch)
    if size <= 8192:
        assert api.parse_docking_preparation_json(raw).model_dump(exclude_unset=True) == proposal()
        assert visited == [True]
    else:
        reject_raw(api, raw)
        assert visited == []


@pytest.mark.parametrize("character", ["中", "🧪"])
@pytest.mark.parametrize("size", [8192, 8193])
def test_utf8_bytes_not_characters_and_not_a_schema_false_positive(character, size, monkeypatch):
    api = contract()
    data = proposal()
    data["kind"] = character * 300  # Deliberately schema-invalid at BOTH sizes.
    raw = wire(data)
    raw += " " * (size - len(raw.encode("utf-8")))
    assert len(raw) < size == len(raw.encode("utf-8"))
    visited = observe_validation(api, monkeypatch)
    reject_raw(api, raw)
    assert visited == ([True] if size == 8192 else [])


@pytest.mark.parametrize("shape", ["array", "object"])
@pytest.mark.parametrize("depth", [7, 8, 9, 16, 17])
def test_depth_boundary_precedes_model_validation(shape, depth, monkeypatch):
    api = contract()
    opening, closing = ("[", "]") if shape == "array" else ('{"x":', "}")
    # Root depth zero; scalar at depth N. Nodes <=35, bytes far below 8192.
    raw = opening * depth + "0" + closing * depth
    visited = observe_validation(api, monkeypatch)
    reject_raw(api, raw)  # Under-limit shapes reach the real schema rejection.
    assert visited == ([True] if depth <= 8 else [])


@pytest.mark.parametrize("shape", ["array", "object"])
@pytest.mark.parametrize("nodes", [255, 256, 257])
def test_node_boundary_counts_keys_and_precedes_model_validation(shape, nodes, monkeypatch):
    api = contract()
    if shape == "array":
        # One root list plus N-1 scalar nodes.
        value = [0] * (nodes - 1)
    else:
        # One root +127 keys +127 scalar values =255. Replacing one scalar
        # with [0] or [0,0] adds exactly one or two nodes, at depth <=2.
        value = {str(i): 0 for i in range(127)}
        if nodes > 255:
            value["0"] = [0] * (nodes - 255)
    raw = json.dumps(value)
    assert len(raw.encode("utf-8")) < 8192
    visited = observe_validation(api, monkeypatch)
    reject_raw(api, raw)
    assert visited == ([True] if nodes <= 256 else [])


def test_native_arguments_and_json_content_have_payload_parity_only():
    api = contract()
    # Literal wire carriers, NOT a transport/request/journal integration test.
    native = {"function": {"name": "docking_preparation", "arguments": MINIMAL}}
    content = {"content": MINIMAL}
    assert api.parse_docking_preparation_json(native["function"]["arguments"]) == (
        api.parse_docking_preparation_json(content["content"])
    )


@pytest.mark.parametrize("envelope", ["decision", "intent", "docking_preparation"])
def test_other_protocol_envelopes_never_admit_a_proposal(envelope):
    reject_raw(contract(), json.dumps({envelope: proposal()}))


def schema_nodes(value):
    # Schema inspection only, not a copy of the DTO's acceptance algorithm.
    if isinstance(value, dict):
        yield value
        for child in value.values():
            yield from schema_nodes(child)
    elif isinstance(value, list):
        for child in value:
            yield from schema_nodes(child)


def resolve(schema, node):
    if "$ref" in node:
        return schema["$defs"][node["$ref"].removeprefix("#/$defs/")]
    if "allOf" in node and len(node["allOf"]) == 1:
        return resolve(schema, node["allOf"][0])
    return node


def test_schema_is_closed_complete_and_fresh_without_authority_fields():
    api = contract()
    schema = api.docking_preparation_json_schema()
    assert schema == api.DockingPreparationEnvelope.model_json_schema()
    assert schema["type"] == "object"
    assert schema["required"] == ["proposal"]
    assert set(schema["properties"]) == {"proposal"}
    inner = resolve(schema, schema["properties"]["proposal"])
    assert set(inner["required"]) == set(inner["properties"]) == PROPOSAL_FIELDS
    props = inner["properties"]
    assert props["version"]["const"] == "1"
    assert props["version"].get("type", "string") == "string"
    assert set(props["kind"]["enum"]) == set(KINDS)
    assert props["unresolved"]["type"] == "boolean"
    assert props["source_spans"]["type"] == "array"
    assert props["source_spans"]["maxItems"] == 16
    spans = resolve(schema, props["source_spans"]["items"])
    assert set(spans["required"]) == set(spans["properties"]) == {"source_id", "start", "end", "role"}
    fields = resolve(schema, props["fields"])
    assert set(fields["properties"]) == INPUT_FIELDS
    assert fields.get("required", []) == []
    for field in fields["properties"].values():
        record = resolve(schema, field)
        assert set(record["required"]) == set(record["properties"]) == {"value", "span_indices"}
        assert not any(node.get("type") == "null" for node in schema_nodes(record))
    for node in schema_nodes(schema):
        if node.get("type") == "object":
            assert node["additionalProperties"] is False
    schema["properties"].clear()
    assert api.docking_preparation_json_schema() == api.DockingPreparationEnvelope.model_json_schema()
    json.dumps(api.docking_preparation_json_schema(), allow_nan=False)
